classDiagram

namespace mtdomecom {
  class MTDomeCom
}

namespace guitool {
  class ControlTabs
  class TabTemplate
}

namespace tab {
  class TabSettings
  class TabInterlock
  class TabBrake
}

TabTemplate <|-- TabSettings
TabTemplate <|-- TabInterlock
TabTemplate <|-- TabBrake

MainWindow *-- Model
MainWindow *-- ControlTabs
MainWindow *-- ControlPanel
MainWindow *-- TabSettings

Model *-- Reporter
Model *-- MTDomeCom

Reporter *-- Status
Reporter *-- SignalInterlock : emit()
Reporter *-- SignalState : emit()
Reporter *-- SignalOperationalMode : emit()
Reporter *-- SignalTelemetry : emit()
Reporter *-- SignalTarget : emit()
Reporter *-- SignalMotion : emit()
Reporter *-- SignalFaultCode : emit()
Reporter *-- SignalConfig : emit()

ControlPanel *-- Model
ControlPanel *-- TabInterlock
ControlPanel *-- TabBrake
ControlPanel --> SignalInterlock : connect()
ControlPanel --> SignalState : connect()

TabSettings *-- Model
TabSettings --> SignalConfig : connect()

TabInterlock *-- Model
TabBrake *-- Model

ControlTabs "1" *-- "9" TabTemplate
