classDiagram

namespace guitool {
  class ControlTabs
  class TabTemplate
}

namespace tab {
  class TabSettings
  class TabInterlock
}

TabTemplate <|-- TabSettings
TabTemplate <|-- TabInterlock

MainWindow *-- Model
MainWindow *-- ControlTabs
MainWindow *-- ControlPanel
MainWindow *-- TabSettings

Model *-- Reporter

Reporter *-- Status
Reporter *-- SignalInterlock : emit()
Reporter *-- SignalState : emit()
Reporter *-- SignalOperationalMode : emit()
Reporter *-- SignalTelemetry : emit()
Reporter *-- SignalTarget : emit()
Reporter *-- SignalMotion : emit()
Reporter *-- SignalFaultCode : emit()

ControlPanel *-- Model
ControlPanel *-- TabInterlock
ControlPanel --> SignalInterlock : connect()
ControlPanel --> SignalState : connect()

TabSettings *-- Model
TabInterlock *-- Model

ControlTabs "1" *-- "9" TabTemplate
