classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
  class Reporter
  class SignalTelemetry
  class SignalFaultCode
  class SignalMotion
  class SignalState
  class SignalTarget
}

Model *-- Reporter

Reporter *-- SignalTelemetry : emit()
Reporter *-- SignalFaultCode : emit()
Reporter *-- SignalMotion : emit()
Reporter *-- SignalState : emit()
Reporter *-- SignalTarget : emit()

TabTemplate <|-- TabElevation
TabTemplate <|-- TabFigure

TabElevation *-- Model
TabElevation "1" *-- "8" TabFigure
TabElevation --> SignalTelemetry : connect()
TabElevation --> SignalFaultCode : connect()
TabElevation --> SignalMotion : connect()
TabElevation --> SignalState : connect()
TabElevation --> SignalTarget : connect()

TabFigure *-- Model
