classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
  class Reporter
  class SignalSensor
}

Model *-- Reporter

Reporter *-- SignalSensor : emit()

TabTemplate <|-- TabSensorFixed

TabSensorFixed *-- Model
TabSensorFixed --> SignalSensor : connect()
