classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
  class Reporter
  class SignalConfig
}

Model *-- Reporter

Reporter *-- SignalConfig : emit()

TabTemplate <|-- TabSettings

TabSettings *-- Model
TabSettings --> SignalConfig : connect()
