classDiagram

namespace guitool {
  class TabTemplate
}

TabTemplate <|-- TabApertureShutter
TabTemplate <|-- TabAzimuth
TabTemplate <|-- TabCalibration
TabTemplate <|-- TabCommand
TabTemplate <|-- TabElevation
TabTemplate <|-- TabFigure
TabTemplate <|-- TabInterlock
TabTemplate <|-- TabLouver
TabTemplate <|-- TabLouverSingle
TabTemplate <|-- TabRearAccessDoor
TabTemplate <|-- TabSelector
TabTemplate <|-- TabSettings
TabTemplate <|-- TabThermalSystem
TabTemplate <|-- TabUtility
