classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
}

TabTemplate <|-- TabLouver
TabTemplate <|-- TabLouverSingle
TabTemplate <|-- TabFigure

TabLouver *-- Model
TabLouver "1" *-- "34" TabLouverSingle
TabLouver *-- TabFigure

TabLouverSingle *-- Model

TabFigure *-- Model
