classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
  class SignalTelemetry
}

Model *-- SignalTelemetry : emit()

TabTemplate <|-- TabLouver
TabTemplate <|-- TabLouverSingle
TabTemplate <|-- TabFigure

TabLouver *-- Model
TabLouver "1" *-- "34" TabLouverSingle
TabLouver *-- TabFigure
TabLouver --> SignalTelemetry : connect()

TabLouverSingle *-- Model

TabFigure *-- Model
