classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
  class Reporter
  class SignalInterlock
}

Model *-- Reporter

Reporter *-- SignalInterlock : emit()

TabTemplate <|-- TabInterlock

TabInterlock *-- Model
TabInterlock --> SignalInterlock : connect()
