classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
  class Reporter
  class SignalTelemetry
  class SignalFaultCode
  class SignalMotion
  class SignalState
}

Model *-- Reporter

Reporter *-- SignalTelemetry : emit()
Reporter *-- SignalFaultCode : emit()
Reporter *-- SignalMotion : emit()
Reporter *-- SignalState : emit()

TabTemplate <|-- TabLouver
TabTemplate <|-- TabLouverSingle
TabTemplate <|-- TabFigure

TabLouver *-- Model
TabLouver "1" *-- "34" TabLouverSingle
TabLouver *-- TabFigure
TabLouver --> SignalTelemetry : connect()
TabLouver --> SignalFaultCode : connect()
TabLouver --> SignalMotion : connect()
TabLouver --> SignalState : connect()

TabLouverSingle *-- Model

TabFigure *-- Model
