classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
  class SignalTelemetry
}

Model *-- SignalTelemetry : emit()

TabTemplate <|-- TabRearAccessDoor
TabTemplate <|-- TabFigure

TabRearAccessDoor *-- Model
TabRearAccessDoor "1" *-- "6" TabFigure
TabRearAccessDoor --> SignalTelemetry : connect()

TabFigure *-- Model
