classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
  class Reporter
  class SignalTelemetry
  class SignalFaultCode
  class SignalMotion
  class SignalState
}

Model *-- Reporter

Reporter *-- SignalTelemetry : emit()
Reporter *-- SignalFaultCode : emit()
Reporter *-- SignalMotion : emit()
Reporter *-- SignalState : emit()

TabTemplate <|-- TabCalibration
TabTemplate <|-- TabFigure

TabCalibration *-- Model
TabCalibration "1" *-- "6" TabFigure
TabCalibration --> SignalTelemetry : connect()
TabCalibration --> SignalFaultCode : connect()
TabCalibration --> SignalMotion : connect()
TabCalibration --> SignalState : connect()

TabFigure *-- Model
