classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
  class Reporter
  class SignalTelemetry
  class SignalFaultCode
  class SignalMotion
  class SignalState
  class SignalTarget
}

Model *-- Reporter

Reporter *-- SignalTelemetry : emit()
Reporter *-- SignalFaultCode : emit()
Reporter *-- SignalMotion : emit()
Reporter *-- SignalState : emit()
Reporter *-- SignalTarget : emit()

TabTemplate <|-- TabAzimuth
TabTemplate <|-- TabFigure

TabAzimuth *-- Model
TabAzimuth "1" *-- "7" TabFigure
TabAzimuth --> SignalTelemetry : connect()
TabAzimuth --> SignalFaultCode : connect()
TabAzimuth --> SignalMotion : connect()
TabAzimuth --> SignalState : connect()
TabAzimuth --> SignalTarget : connect()

TabFigure *-- Model
