classDiagram

namespace guitool {
  class TabTemplate
}

namespace mtdomegui {
  class Model
  class SignalOperationalMode
  class SignalTelemetry
}

Model *-- SignalOperationalMode : emit()
Model *-- SignalTelemetry : emit()

TabTemplate <|-- TabUtility

TabUtility *-- Model
TabUtility --> SignalOperationalMode : connect()
TabUtility --> SignalTelemetry : connect()
